on: [push]

jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
    - uses: KTH-dESA/GEOSeMOSYS_Kenya/sphinx-pages@master
      with:
        github_token: ${{ secrets.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 }}
        create_readme: true